### ISSUE TITLE
card component

### ISSUE THREAD

**Issue by Dami-LEE00** [codingBottle/codingBottle-WEB-01-rerave#15]
## 설명
 Rerave Technology 페이지에 들어갈 카드 컴포를 개발합니다.
## 할 일
- [x] 마크업
- [x] 스타일 설정

**Comment by hanseulhee** [comment]
@Dami-LEE00 ㅋㅋㅋㅋㅋ 왜 저를 ?!?

**Comment by Dami-LEE00** [comment]
> @Dami-LEE00 ㅋㅋㅋㅋㅋ 왜 저를 ?!?

헉 착각했어요!!! 🤢🤢🤢
